In [0]:
# Meus outros cursos: https://linktr.ee/rafaelfvcs

In [0]:
import pandas as pd

In [0]:
df = pd.read_csv("https://cdncontribute.geeksforgeeks.org/wp-content/uploads/nba.csv")

In [0]:
df.head(4)

            Name            Team  Number  ... Weight            College     Salary
0  Avery Bradley  Boston Celtics     0.0  ...  180.0              Texas  7730337.0
1    Jae Crowder  Boston Celtics    99.0  ...  235.0          Marquette  6796117.0
2   John Holland  Boston Celtics    30.0  ...  205.0  Boston University        NaN
3    R.J. Hunter  Boston Celtics    28.0  ...  185.0      Georgia State  1148640.0

[4 rows x 9 columns]

In [0]:
df.shape

(458, 9)

In [0]:
stack_df = df.stack()

In [0]:
stack_df

0    Name            Avery Bradley
     Team           Boston Celtics
     Number                      0
     Position                   PG
     Age                        25
     Height                    6-2
     Weight                    180
     College                 Texas
     Salary            7.73034e+06
1    Name              Jae Crowder
     Team           Boston Celtics
     Number                     99
     Position                   SF
     Age                        25
     Height                    6-6
     Weight                    235
     College             Marquette
     Salary            6.79612e+06
2    Name             John Holland
     Team           Boston Celtics
     Number                     30
     Position                   SG
     Age                        27
     Height                    6-5
     Weight                    205
     College     Boston University
3    Name              R.J. Hunter
     Team           Boston Celtics
     Number                     28
     Position                   SG
                       ...
453  Age                        26
     Height                    6-3
     Weight                    203
     College                Butler
     Salary            2.43333e+06
454  Name                Raul Neto
     Team                Utah Jazz
     Number                     25
     Position                   PG
     Age                        24
     Height                    6-1
     Weight                    179
     Salary                 900000
455  Name             Tibor Pleiss
     Team                Utah Jazz
     Number                     21
     Position                    C
     Age                        26
     Height                    7-3
     Weight                    256
     Salary                2.9e+06
456  Name              Jeff Withey
     Team                Utah Jazz
     Number                     24
     Position                    C
     Age                        26
     Height                    7-0
     Weight                    231
     College                Kansas
     Salary                 947276
Length: 4018, dtype: object

In [0]:
udf = stack_df.unstack()

In [0]:
udf.head(3)

            Name            Team Number  ... Weight            College       Salary
0  Avery Bradley  Boston Celtics      0  ...    180              Texas  7.73034e+06
1    Jae Crowder  Boston Celtics     99  ...    235          Marquette  6.79612e+06
2   John Holland  Boston Celtics     30  ...    205  Boston University          NaN

[3 rows x 9 columns]