In [0]:
# Meus outros cursos: https://linktr.ee/rafaelfvcs

In [0]:
import pandas as pd

In [0]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
   ...:                     'B': ['B0', 'B1', 'B2', 'B3'],
   ...:                     'C': ['C0', 'C1', 'C2', 'C3'],
   ...:                     'D': ['D0', 'D1', 'D2', 'D3']},
   ...:                     index=[0, 1, 2, 3])

In [0]:
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
   ...:                     'B': ['B4', 'B5', 'B6', 'B7'],
   ...:                     'C': ['C4', 'C5', 'C6', 'C7'],
   ...:                     'D': ['D4', 'D5', 'D6', 'D7']},
   ...:                      index=[4, 5, 6, 7])

In [0]:
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
   ...:                     'B': ['B8', 'B9', 'B10', 'B11'],
   ...:                     'C': ['C8', 'C9', 'C10', 'C11'],
   ...:                     'D': ['D8', 'D9', 'D10', 'D11']},
   ...:                     index=[8, 9, 10, 11])

In [0]:
m = pd.merge(df1,df2, on=['A','C'], how="inner")

In [0]:
m

Empty DataFrame
Columns: [A, B_x, C, D_x, B_y, D_y]
Index: []

In [0]:
df1

In [0]:
df2

In [0]:
df3

In [0]:
frames = [df1, df2, df3]

In [0]:
frames

In [0]:
type(frames)

list

In [0]:
framesCombinados = pd.concat(frames)

In [0]:
framesCombinados

In [0]:
type(framesCombinados)

pandas.core.frame.DataFrame

In [0]:
framesCombinados2 = pd.concat([df1,df2,df3])

In [0]:
?pd.concat()

In [0]:
framesCombinados2

In [0]:
grupo = pd.concat([df1,df2,df3], keys=['f1','f2','f3'])

In [0]:
grupo

         A    B    C    D
f1 0    A0   B0   C0   D0
   1    A1   B1   C1   D1
   2    A2   B2   C2   D2
   3    A3   B3   C3   D3
f2 4    A4   B4   C4   D4
   5    A5   B5   C5   D5
   6    A6   B6   C6   D6
   7    A7   B7   C7   D7
f3 8    A8   B8   C8   D8
   9    A9   B9   C9   D9
   10  A10  B10  C10  D10
   11  A11  B11  C11  D11

In [0]:
grupo['A']

f1  0      A0
    1      A1
    2      A2
    3      A3
f2  4      A4
    5      A5
    6      A6
    7      A7
f3  8      A8
    9      A9
    10    A10
    11    A11
Name: A, dtype: object

In [0]:
grupo.loc['f1']

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [0]:
# Outra maneira de concatenar

In [0]:
g2 = df1.append(df2)

In [0]:
g2

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [0]:
g2.append(df3)

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [0]:
g4 = df1.append(df2).append(df3)

In [0]:
g4

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [0]:
s1 = pd.Series(['S0', 'S1', 'S2', 'S3'], name='Serie')

In [0]:
dg = pd.concat([df1, df2], axis=1)

In [0]:
dg

     0    1    2    3    4    5    6    7
0   A0   B0   C0   D0  NaN  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN  NaN
2   A2   B2   C2   D2  NaN  NaN  NaN  NaN
3   A3   B3   C3   D3  NaN  NaN  NaN  NaN
4  NaN  NaN  NaN  NaN   A4   B4   C4   D4
5  NaN  NaN  NaN  NaN   A5   B5   C5   D5
6  NaN  NaN  NaN  NaN   A6   B6   C6   D6
7  NaN  NaN  NaN  NaN   A7   B7   C7   D7

In [0]:
dg2 = pd.concat([df1, s1, df2], axis=1)

In [0]:
dg2

     A    B    C    D Serie    A    B    C    D
0   A0   B0   C0   D0    S0  NaN  NaN  NaN  NaN
1   A1   B1   C1   D1    S1  NaN  NaN  NaN  NaN
2   A2   B2   C2   D2    S2  NaN  NaN  NaN  NaN
3   A3   B3   C3   D3    S3  NaN  NaN  NaN  NaN
4  NaN  NaN  NaN  NaN   NaN   A4   B4   C4   D4
5  NaN  NaN  NaN  NaN   NaN   A5   B5   C5   D5
6  NaN  NaN  NaN  NaN   NaN   A6   B6   C6   D6
7  NaN  NaN  NaN  NaN   NaN   A7   B7   C7   D7